assays:
    - n_trials: 5
      trial_duration: 10.0
      force_field:
          enabled: false
          matrix: [0.0, 0.0, 0.0, 0.0]
    - n_trials: 5
      trial_duration: 10.0
      force_field:
          enabled: true
          matrix: [1.0, 0.5, -0.5, 1.0]
    - n_trials: 5
      trial_duration: 10.0
      force_field:
          enabled: true
          matrix: [-1.0, 0.2, 0.2, -1.0] 